//! Bytecode emitter

use thiserror::Error;

/// Error during code generation
#[derive(Debug, Error)]
pub enum EmitError {
    #[error("Unsupported MIR node: {0}")]
    UnsupportedNode(String),

    #[error("Code generation error: {0}")]
    EmitError(String),
}

pub type Result<T> = std::result::Result<T, EmitError>;

/// A chunk of generated bytecode
#[derive(Debug, Default)]
pub struct BytecodeChunk {
    pub code: String,
    pub labels: Vec<(String, usize)>,
}

impl BytecodeChunk {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn add_line(&mut self, line: &str) {
        self.code.push_str(line);
        self.code.push('\n');
    }

    pub fn extend(&mut self, other: &BytecodeChunk) {
        self.code.push_str(&other.code);
    }
}

/// Code emitter interface
pub trait CodeEmitter {
    fn emit_program(&mut self, program: &nevermind_mir::MirProgram) -> Result<BytecodeChunk>;

    fn emit_function(&mut self, func: &nevermind_mir::MirFunction) -> Result<BytecodeChunk>;

    fn emit_expr(&mut self, expr: &nevermind_mir::MirExpr) -> Result<BytecodeChunk>;
}